add initial tmux support

diff --git a/sysup b/sysup
--- a/sysup
+++ b/sysup
@@ -11,28 +11,6 @@ function onSigInt() {
   START=0
 }
 
-CLEANED=0
-NOSYNC=0
-SYNC=0
-NOPORTAGE=0
-PORTAGE=0
-NOREBUILD=0
-REBUILD=0
-NOCLEAN=0
-CLEAN=0
-QUIET=0
-NOUPDATE=0
-UPDATE=0
-FIXPERL=0
-RESUME=0
-NOASK=0
-SKIPFIRST=0
-
-[ ! -f /etc/sysup/sysup.conf ] && (echo "Config not found"; exit 1)
-
-. /etc/sysup/sysup.conf
-
-
 function usage() {
   echo -e "$0 [-nc] [-ns] [-np] [-nr] [-fp] [-r] [-q] [-na]\n"
   echo "Options:"
@@ -53,6 +31,128 @@ function usage() {
   echo "    --clean, -c        - clean phase"
   exit 0
 }
+
+# show duration per part
+function printDuration() {
+  local totaltime=0
+  local MAX=0
+  for TIME in ${TIMES[@]};do
+    let totaltime=totaltime+TIME
+  done
+  for NAME in ${PARTNAMES[@]};do
+    if [ $MAX -lt ${#NAME} ];then
+      MAX=${#NAME}
+    fi
+  done
+
+  echo
+  local -A LEN
+  for PART in ${PARTS[@]};do
+    if [[ ${TIMES[$PART]} > 0 ]];then
+      local len
+      local offset
+      local offset2
+      LEN[$PART]=${#PARTNAMES[$PART]}
+
+      if [ ${LEN[$PART]} -gt 8 ]; then
+        let len=${LEN[$PART]}+2
+      else
+        len=10
+      fi
+
+      let offset=($len-${LEN[$PART]})/2
+      if [ $((${LEN[$PART]}%2)) -eq 0 ];then
+        offset2=$offset
+      else
+        let offset2=offset+1
+      fi
+      printf "\e[4m%${offset}s%s%${offset2}s" " " "${PARTNAMES[$PART]}" " " >&2
+      if [[ "$PART" != "${PARTS[-1]}" ]];then
+        printf "|" >&2
+      fi
+    fi
+  done
+  printf "\e[0m\n" >&2
+  for PART in ${PARTS[@]};do
+    if [[ ${TIMES[$PART]} > 0 ]];then
+      local offset=1
+      local offset2
+      if [ ${LEN[$PART]} -gt 8 ];then
+        let offset=(${LEN[$PART]}-6)/2
+      fi
+      if [[ $((${LEN[$PART]}%2)) -eq 0 ]];then
+        offset2=$offset
+      else
+        let offset2=offset+1
+      fi
+
+      printf "%${offset}s" " " >&2
+      DD=`date -u -d @${TIMES[$PART]} "+%H:%M:%S"`
+      echo -ne "\e[1m$DD\e[0m" >&2
+      printf "%${offset2}s" " " >&2
+      if [[ "$PART" != "${PARTS[-1]}" ]];then
+        echo -n "|" >&2
+      fi
+    fi
+  done
+
+  echo -ne "\n\nTotal: \e[1m" >&2
+  date -u -d @$totaltime "+%-Hh %-Mm %-Ss" >&2
+  echo -en "\e[0m"
+}
+
+# Check return codes
+function checkError() {
+  if [ $1 != 0 ];then
+    if [[ "x$2" != "x" ]];then
+      echo -e "[\e[1;31mE\e[0m] $2 ($1)" >&2
+    fi
+    exit $1
+  fi
+}
+
+# Start a subprocess and pipe output to a log
+function startSubProcess() {
+  if [ $CLEANED -eq 1 ] || [ $START -ne 1 ]; then
+    return
+  fi
+  if [ ${CMDS[$3$1]+x} ];then
+    if [ $QUIET -eq 1 ];then
+      ${CMDS[$3$1]} 2>&1 >> "$2"
+      RC[$3$1]=${PIPESTATUS[0]}
+    else
+      ${CMDS[$3$1]} 2>&1 | tee -ia "$2"
+      RC[$3$1]=${PIPESTATUS[0]}
+    fi
+  fi
+}
+
+# Run a single part with pre- and post- script if defined
+function processPart() {
+  if [ $CLEANED -eq 1 ] || [ $START -ne 1 ]; then
+    return
+  fi
+
+  local endtime
+  local starttime=`date  "+%s"`
+  local LOGFILE="$LOGPATH/${1,,}_$(eval date +%Y%m%d%H%M%S).log"
+  printf "\e[1m[%s - %s] Starting %s Phase\e[0m\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >&2
+  printf "[%s - %s] Starting %s Phase\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >>$LOGFILE
+
+  startSubProcess "$1" "$LOGFILE" "PRE"
+  startSubProcess "$1" "$LOGFILE"
+  startSubProcess "$1" "$LOGFILE" "POST"
+
+  endtime=`date  "+%s"`
+  let TIMES[$1]=endtime-starttime
+  printf "[%s - %s] %s Phase Done\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >>$LOGFILE
+  checkError ${RC[$1]} ${ERROR_MESSAGE[$1]}
+}
+
+[ ! -f /etc/sysup/sysup.conf ] && (echo "Config not found"; exit 1)
+. /etc/sysup/sysup.conf
+
+# parse parameters
 PARAMS="$@"
 while [ "$1x" != "x" ];do
   var="${1^^}"
@@ -131,6 +231,13 @@ while [ "$1x" != "x" ];do
   shift
 done
 
+# check validity of parameters
+if [ $(($REBUILD+$UPDATE+$CLEAN+$SYNC+$PORTAGE)) -gt 0 ] && [ $((RESUME+FIXPERL)) -gt 0 ];then
+  echo -e "\e[33mdon't know what to do :/\e[0m" >&2
+  exit 1  
+fi
+
+# disable not needed parts
 if [ $(($REBUILD+$UPDATE+$CLEAN+$SYNC+$PORTAGE)) -gt 0 ];then
   NOSYNC=1
   NOPORTAGE=1
@@ -139,16 +246,24 @@ if [ $(($REBUILD+$UPDATE+$CLEAN+$SYNC+$PORTAGE)) -gt 0 ];then
   NOCLEAN=1
 fi
 
+# Runcheck
 if [ -f "$LOCKFILE" ]; then
   echo "Update is running (PID:`cat $LOCKFILE`)"
   exit 1
 fi
 
+# get root if needed
 if [ $EUID -ne 0 ];then
   SUDO_BIN=$(which sudo 2>/dev/null)
   [ -z $SUDO_BIN ] && exec $(which su) - -c "\"$(realpath "$0")\" $PARAMS" || exec ${SUDO_BIN} "$(realpath "$0")" $PARAMS
   echo "undefined error" >&2
   exit 1
+fi
+
+# open tmux if needed
+TMUXBIN=$(which tmux 2>/dev/null)
+if [ ${#TMUX} -eq 0 ] && [ ${#TMUXBIN} -gt 0 ];then
+  exec $TMUXBIN new-session -s sysup "\"$(realpath "$0")\" $PARAMS; read -n1 -p'Warte auf Tastendruck...' -s && echo"
 fi
 
 declare -i START=0
@@ -158,125 +273,16 @@ declare -a PARTS
 declare -A CMDS
 declare -A ERROR_MESSAGE
 declare -A PARTNAMES
+declare -i CLEANED=0
 
+# define destructor and sigint-handler
 trap cleanup EXIT
 trap onSigInt INT
 
+# write lockfile for runcheck
 echo $$ > "$LOCKFILE"
 
-function printDuration() {
-  local totaltime=0
-  local MAX=0
-  for TIME in ${TIMES[@]};do
-    let totaltime=totaltime+TIME
-  done
-  for NAME in ${PARTNAMES[@]};do
-    if [ $MAX -lt ${#NAME} ];then
-      MAX=${#NAME}
-    fi
-  done
-
-  echo
-  local -A LEN
-  for PART in ${PARTS[@]};do
-    if [[ ${TIMES[$PART]} > 0 ]];then
-      local len
-      local offset
-      local offset2
-      LEN[$PART]=${#PARTNAMES[$PART]}
-
-      if [ ${LEN[$PART]} -gt 8 ]; then
-        let len=${LEN[$PART]}+2
-      else
-        len=10
-      fi
-
-      let offset=($len-${LEN[$PART]})/2
-      if [ $((${LEN[$PART]}%2)) -eq 0 ];then
-        offset2=$offset
-      else
-        let offset2=offset+1
-      fi
-      printf "\e[4m%${offset}s%s%${offset2}s" " " "${PARTNAMES[$PART]}" " " >&2
-      if [[ "$PART" != "${PARTS[-1]}" ]];then
-        printf "|" >&2
-      fi
-    fi
-  done
-  printf "\e[0m\n" >&2
-  for PART in ${PARTS[@]};do
-    if [[ ${TIMES[$PART]} > 0 ]];then
-      local offset=1
-      local offset2
-      if [ ${LEN[$PART]} -gt 8 ];then
-        let offset=(${LEN[$PART]}-6)/2
-      fi
-      if [[ $((${LEN[$PART]}%2)) -eq 0 ]];then
-        offset2=$offset
-      else
-        let offset2=offset+1
-      fi
-
-      printf "%${offset}s" " " >&2
-      DD=`date -u -d @${TIMES[$PART]} "+%H:%M:%S"`
-      echo -ne "\e[1m$DD\e[0m" >&2
-      printf "%${offset2}s" " " >&2
-      if [[ "$PART" != "${PARTS[-1]}" ]];then
-        echo -n "|" >&2
-      fi
-    fi
-  done
-
-  echo -ne "\n\nTotal: \e[1m" >&2
-  date -u -d @$totaltime "+%-Hh %-Mm %-Ss" >&2
-  echo -en "\e[0m"
-}
-
-function checkError() {
-  if [ $1 != 0 ];then
-    if [[ "x$2" != "x" ]];then
-      echo -e "[\e[1;31mE\e[0m] $2 ($1)" >&2
-    fi
-    exit $1
-  fi
-}
-
-function startSubProcess() {
-  if [ $CLEANED -eq 1 ] || [ $START -ne 1 ]; then
-    return
-  fi
-  if [ ${CMDS[$3$1]+x} ];then
-    if [ $QUIET -eq 1 ];then
-      ${CMDS[$3$1]} 2>&1 >> "$2"
-      RC[$3$1]=${PIPESTATUS[0]}
-    else
-      ${CMDS[$3$1]} 2>&1 | tee -ia "$2"
-      RC[$3$1]=${PIPESTATUS[0]}
-    fi
-  fi
-}
-
-function processPart() {
-  if [ $CLEANED -eq 1 ] || [ $START -ne 1 ]; then
-    return
-  fi
-
-  local endtime
-  local starttime=`date  "+%s"`
-  local LOGFILE="$LOGPATH/${1,,}_$(eval date +%Y%m%d%H%M%S).log"
-  printf "\e[1m[%s - %s] Starting %s Phase\e[0m\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >&2
-  printf "[%s - %s] Starting %s Phase\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >>$LOGFILE
-
-  startSubProcess "$1" "$LOGFILE" "PRE"
-  startSubProcess "$1" "$LOGFILE"
-  startSubProcess "$1" "$LOGFILE" "POST"
-
-  endtime=`date  "+%s"`
-  let TIMES[$1]=endtime-starttime
-  printf "[%s - %s] %s Phase Done\n" "$(eval date +%d.%m.%Y)" "$(eval date +%R:%S)" "${PARTNAMES[$1]}" >>$LOGFILE
-  checkError ${RC[$1]} ${ERROR_MESSAGE[$1]}
-}
-
+# add required parts
 if [ $NOSYNC -eq 0 ] || [ $SYNC -eq 1 ];then
   PARTS[${#PARTS[@]}]="SYNC"
 fi
@@ -313,6 +319,7 @@ fi
 START=1
 [ -f /etc/sysup/pre.sh ] && source /etc/sysup/pre.sh
 
+# run parts
 for PART in ${PARTS[@]}; do
   if [ $CLEANED -eq 1 ] || [ $START -ne 1 ]; then
     break
